
name: Deploy Bicep file
on: [workflow_dispatch]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        region: centralus
        template: ./workload/bicep/deploy-baseline.bicep
        parameters: ./workload/bicep/parameters/deploy-baseline-parameters-example.json avdWorkloadSubsId=${{ secrets.AZURE_SUBSCRIPTION }} deploymentPrefix=avd9 avdVmLocalUserName=${{ secrets.AVDVMLOCALUSERNAME }} avdVmLocalUserPassword=${{ secrets.AVDVMLOCALUSERPASSWORD }} avdIdentityServiceProvider=ADDS avdEnterpriseAppObjectId=${{ secrets.AVDENTERPRISEAPPOBJECTID }} avdDeployMonitoring=false createAvdVnet=false createAvdFslogixDeployment=true createPrivateDnsZones=true deployAlaWorkspace=false avdSessionHostLocation=centralus avdManagementPlaneLocation=centralus existingVnetAvdSubnetResourceId=/subscriptions/0f07e41f-4fbd-45c4-b9a0-3f83193ba03b/resourceGroups/rg_ServerLabCentral/providers/Microsoft.Network/virtualNetworks/vnetProd01/subnets/default identityDomainName=${{ secrets.AD_NAME}} avdDomainJoinUserName=${{ secrets.AD_JOIN_USER }} avdDomainJoinUserPassword=${{ secrets.AD_JOIN_PASS }}
        
